project:
  type: website
  output-dir: docs

website:
  title: "Have A Box"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ali.qmd
        text: Muhammad Ali
      - href: mike.qmd
        text: Mike Tyson
      - href: floyd.qmd
        text: Floyd Mayweather
      - href: alvarez.qmd
        text: Canelo Álvarez
      - href: about.qmd
    logo: images/logo.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



